### ISSUE TITLE
Test failures on 32bit platforms in TestMap

### ISSUE THREAD

**Issue by davide125** [xaionaro-go/atomicmap#3]
When building for i686 or armv7hl:
```
--- FAIL: TestMap (0.00s)
panic: unaligned 64-bit atomic operation [recovered]
	panic: unaligned 64-bit atomic operation
goroutine 6 [running]:
testing.tRunner.func1.2(0x5ec908, 0x607168)
	/usr/lib/golang/src/testing/testing.go:1143 +0x294
testing.tRunner.func1(0x1801340)
	/usr/lib/golang/src/testing/testing.go:1146 +0x3b4
panic(0x5ec908, 0x607168)
	/usr/lib/golang/src/runtime/panic.go:965 +0x188
runtime/internal/atomic.panicUnaligned()
	/usr/lib/golang/src/runtime/internal/atomic/unaligned.go:8 +0x2c
runtime/internal/atomic.Load64(0x18660cc, 0x0, 0x18660c0)
	/usr/lib/golang/src/runtime/internal/atomic/asm_arm.s:263 +0x14
github.com/xaionaro-go/atomicmap.(*openAddressGrowingMap).Len(0x18660c0, 0x0)
	/builddir/build/BUILD/atomicmap-024139dbbfbc1938f0c24e61b3971274f23780c6/_build/src/github.com/xaionaro-go/atomicmap/open_growing_map.go:663 +0x28
github.com/xaionaro-go/atomicmap/internal/benchmarkRoutines.DoTest(0x1801340, 0x606bec)
	/builddir/build/BUILD/atomicmap-024139dbbfbc1938f0c24e61b3971274f23780c6/_build/src/github.com/xaionaro-go/atomicmap/internal/benchmarkRoutines/test_routines.go:34 +0x50
github.com/xaionaro-go/atomicmap.TestMap(0x1801340)
	/builddir/build/BUILD/atomicmap-024139dbbfbc1938f0c24e61b3971274f23780c6/_build/src/github.com/xaionaro-go/atomicmap/open_growing_map_test.go:12 +0x28
testing.tRunner(0x1801340, 0x606be8)
	/usr/lib/golang/src/testing/testing.go:1193 +0xd8
created by testing.(*T).Run
	/usr/lib/golang/src/testing/testing.go:1238 +0x254
exit status 2
FAIL	github.com/xaionaro-go/atomicmap	0.011s
```
You can see the full logs on https://koji.fedoraproject.org/koji/taskinfo?taskID=70369444 and https://koji.fedoraproject.org/koji/taskinfo?taskID=70369445 (look at build.log).

**Comment by xaionaro** [comment]
Thank you!

Will fix tomorrow... I hope I won't forget :)

**Comment by xaionaro** [comment]
BTW, may I ask: do you use this package for your project, or it is a dependency of another project?

**Comment by davide125** [comment]
It's a transitive dependency for https://github.com/facebookincubator/contest (which is what I'm trying to package in Fedora).

**Comment by xaionaro** [comment]
O, wow. It was a mistake from my side. `atomicmap` isn't really used in contest. It is just mentioned in `go.sum` (and should be removed from there). Also need to do not forget :)

**Comment by xaionaro** [comment]
Added a commit. I'm not sure if it helped. But should in theory.

**Comment by xaionaro** [comment]
OK, it appears atomicmap indeed is used in contest, but in the module (`tsmetrics`), which is not actually used:
```
xaionaro@void:~/go/src/github.com/facebookincubator/contest$ go mod graph | grep atomicmap
github.com/xaionaro-go/metrics@v0.0.0-20210425194006-68050b337673 github.com/xaionaro-go/atomicmap@v0.0.0-20200307233044-c040bc137895
github.com/xaionaro-go/atomicmap@v0.0.0-20200307233044-c040bc137895 github.com/OneOfOne/xxhash@v1.2.7
github.com/xaionaro-go/atomicmap@v0.0.0-20200307233044-c040bc137895 github.com/cornelk/hashmap@v1.0.1
github.com/xaionaro-go/atomicmap@v0.0.0-20200307233044-c040bc137895 github.com/xaionaro-go/spinlock@v0.0.0-20190309154744-55278e21e817
```
This module was added as optional for `xcontext`, which is planned to be separated to another project. OK, it seems there's no quick fix for that (but to delete `tsmetrics`).

@davide125 : Did the fix in my previous comment help?

**Comment by davide125** [comment]
Yep, looks like that worked, thanks! Builds are now passing on all architectures: https://koji.fedoraproject.org/koji/taskinfo?taskID=70506397

**Comment by xaionaro** [comment]
Thank you for the bugreport and for the testing! Closing the issue for now.
